image: kasproject/kas:0.14.0

variables:
  GIT_STRATEGY: clone

.build: &build
  stage: build
  script:
    # define these proxy variables in your CI/CD settings as needed
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - cd ..
    - kas build meta-iot2000/$KAS_CONFIG

.build-and-deploy-image: &build-and-deploy-image
  <<: *build
  after_script:
    - xz -c -T0 ../build/tmp/deploy/images/iot2000/$DEPLOY_IMAGE.wic > $DEPLOY_IMAGE.xz
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHA::12}"
    paths:
      - $DEPLOY_IMAGE.xz
    expire_in: 1 week

.build-and-deploy-sdk: &build-and-deploy-sdk
  <<: *build
  after_script:
    - mv ../build/tmp/deploy/sdk/$DEPLOY_SDK .
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHA::12}"
    paths:
      - $DEPLOY_SDK
    expire_in: 1 week

bsp:
  <<: *build-and-deploy-image
  variables:
    KAS_CONFIG: meta-iot2000-bsp/kas.yml
    DEPLOY_IMAGE: core-image-minimal-iot2000

example-image:
  <<: *build-and-deploy-image
  variables:
    KAS_CONFIG: meta-iot2000-example/kas.yml
    DEPLOY_IMAGE: iot2000-example-image-iot2000

windows-sdk:
#  <<: *build-and-deploy-sdk
  <<: *build
  variables:
    KAS_CONFIG: meta-iot2000-example/kas-sdk-windows-i586.yml
    DEPLOY_SDK: poky-iot2000-glibc-i686-iot2000-example-image-i586-nlp-32-toolchain-2.2.2.tar.xz
